# Generated by Django 4.2.28 on 2026-02-26 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('prediction', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('config', models.JSONField(default=dict, help_text='Model configuration parameters')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Config',
                'verbose_name_plural': 'AI Model Configs',
                'db_table': 'advisor_ai_model_configs',
            },
        ),
        migrations.CreateModel(
            name='SuggestedPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(max_length=500)),
                ('category', models.CharField(choices=[('general', 'General'), ('portfolio', 'Portfolio'), ('stock', 'Stock Analysis'), ('learning', 'Learning'), ('strategy', 'Strategy')], default='general', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(default='💬', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Suggested Prompt',
                'verbose_name_plural': 'Suggested Prompts',
                'db_table': 'advisor_suggested_prompts',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('daily', 'Daily Summary'), ('weekly', 'Weekly Analysis'), ('monthly', 'Monthly Review'), ('custom', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('content', models.JSONField(default=dict, help_text='Structured report content')),
                ('key_metrics', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio Report',
                'verbose_name_plural': 'Portfolio Reports',
                'db_table': 'advisor_portfolio_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold'), ('watch', 'Watch')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reasoning', models.TextField()),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('timeframe', models.CharField(default='3-6 months', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('was_successful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='prediction.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Recommendation',
                'verbose_name_plural': 'Investment Recommendations',
                'db_table': 'advisor_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('session_type', models.CharField(choices=[('general', 'General Advice'), ('portfolio', 'Portfolio Analysis'), ('stock', 'Stock Analysis'), ('strategy', 'Investment Strategy')], default='general', max_length=20)),
                ('context_data', models.JSONField(blank=True, default=dict, help_text='Context data for the session')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'db_table': 'advisor_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('ai', 'AI')], max_length=10)),
                ('content', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata')),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisor.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'db_table': 'advisor_chat_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
